markdown: rdiscount
permalink: /:title/
url: http://bohsu.github.com
name: bohsu.github.com
author: Bohsu
qq: 986959080
email: ibohsu@gmail.com
duoshuo: bohsu
#beian: 
#cnzz: 119959
weibo: 2251878243
github: Bohsu
pygments: true
safe: true
paginate: 20
about: "这里是 徐博 的个人博客，创建于 2014 年。使用 Jekyll @ GitHub。<br /><br />"
